# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shuck Productions
email: productions@shuck.org.uk
description: Shuck Productions create new media content for you. Work with us on many different projects from factual to fictional productions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shuckproductions.org.uk" # the base hostname & protocol for your site

#social
twitter_username: shuckproduction
facebook_username: shuckproduction
instagram_username: shuckproduction
youtube_channel_id: UCVyJVvAwP48xrcMMCfANnyA
mail_address: 'productions@shuck.org.uk'


# Build settings
markdown: kramdown
